### ISSUE TITLE
Adicionar Ruby CWB no Grupo Ruby Brasil

### ISSUE THREAD

**Issue by eduardoyutaka** [guru-br/guru-br.github.io#14]
Olá! Tomei a liberdade de criar uma PR para adicionar o Ruby CWB.

Como não temos logo, utilizei uma que está repetida em outros projetos, espero que não seja um problema

https://github.com/guru-br/guru-br.github.io/pull/13

Vou colocar também a screenshot com a mudança visual
<img width="1512" alt="Screenshot 2024-05-15 at 18 19 55" src="https://github.com/guru-br/guru-br.github.io/assets/11102698/45497305-03fe-453f-86eb-28a631d5614c">

**Comment by juuh42dias** [comment]
Merge feito 👍🏼 🚀
